[package]
name = "rust-command-line-tool"
version = "0.1.0"
authors = ["tonytao <tony.tao@zip.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
